### ISSUE TITLE
Totally SAME count matrix(generated) compared to the reference data

### ISSUE THREAD

**Issue by XiaPoppy** [SONGDONGYUAN1994/scDesign3#14]
Hi Dongyuan,

Good news is that I run tutorial simulating batch effect again(take a new subset of my own data) and codes work for my own data now. But a new problem is that the generated count matrix is totally the same as before. I am wondering if the reason is the many 0 in the original matrix. (Codes and data source below)

```r
example_sce <- read_h5ad('./cite_500gene.h5ad')#one modality-several cell types with batch
example_sce<-AnnData2SCE(example_sce)
```

```r
BATCH_data <- construct_data(
  sce = example_sce, #SCE object, ref data
  assay_use = "counts",#'counts','celltype', 'pseudotime' or 'spatial'.
  celltype = "cell_type", 
  pseudotime = NULL,
  spatial = NULL,
  other_covariates = c("batch"),#provided in example_sce colData
  corr_by = "1"
)
BATCH_marginal <- fit_marginal(
  data = BATCH_data,
  predictor = "gene", #intermediate variable name, not matter
  mu_formula = "cell_type + batch", 
  sigma_formula = "1",
  family_use = "nb",
  n_cores = 1, #can be changed to more, some errors may appear, and large value -> save time
  usebam = FALSE
)
set.seed(123)
BATCH_copula <- fit_copula(
  sce = example_sce,
  assay_use = "counts",
  marginal_list = BATCH_marginal,
  family_use = "nb",
  copula = "vine",#determine the copula function, can be changed to gaussian. decide the dependence structure of genes
  n_cores = 1,
  new_covariate = NULL,
  input_data = BATCH_data$dat
)
```
```r
BATCH_marginal_alter <- lapply(BATCH_marginal, function(x) {
  x$fit$coefficients[length(x$fit$coefficients)] <- rnorm(1, mean = 5, sd = 2) #change to 0 for batch correction
  x
})

BATCH_para_alter <- extract_para(
  sce = example_sce,
  marginal_list = BATCH_marginal_alter,
  n_cores = 1,
  family_use = "nb",
  new_covariate = NULL,
  data = BATCH_data$dat
)

set.seed(123)
BATCH_newcount_alter <- simu_new(
  sce = example_sce,
  mean_mat = BATCH_para_alter$mean_mat,
  sigma_mat = BATCH_para_alter$sigma_mat,
  zero_mat = BATCH_para_alter$zero_mat,
  quantile_mat = NULL,
  copula_list = BATCH_copula$copula_list,
  n_cores = 1,
  family_use = "nb",
  input_data = BATCH_data$dat,
  new_covariate = BATCH_data$newCovariate,
  important_feature = BATCH_copula$important_feature
)
BATCH_para_alter <- extract_para(
  sce = example_sce,
  marginal_list = BATCH_marginal_alter,
  n_cores = 1,
  family_use = "nb",
  new_covariate = NULL,
  data = BATCH_data$dat
)

set.seed(123)
BATCH_newcount_alter <- simu_new(
  sce = example_sce,
  mean_mat = BATCH_para_alter$mean_mat,
  sigma_mat = BATCH_para_alter$sigma_mat,
  zero_mat = BATCH_para_alter$zero_mat,
  quantile_mat = NULL,
  copula_list = BATCH_copula$copula_list,
  n_cores = 1,
  family_use = "nb",
  input_data = BATCH_data$dat,
  new_covariate = BATCH_data$newCovariate,
  important_feature = BATCH_copula$important_feature
)
simu_sce <- example_sce
counts(simu_sce) <- BATCH_newcount_alter
logcounts(simu_sce) <- log1p(counts(simu_sce))
´´´
```
I use the CITE-seq data downloaded from [here](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE194122), and take the subset of first 500 gex and first 2 batches 's1d1' and 's1d2'. 

Thanks a lot in advance!

Best,
Danyang

**Comment by SONGDONGYUAN1994** [comment]
Hi Xia,
That sounds crazy! For clarification, you mean that the simulated counts are identical to the reference counts, right? Could you please check the following things?

1. Check if the two matrices are really the same -- sorry for asking this, but we have to confirm this again.
2. Check the `BATCH_para_alter$mean_mat`. If they are all 0, then the result is expected since 0 will always return 0 back.
3. Change `set.seed(123)` to another seed. It should give you another random result, if everything works correctly.

Let me know how it works!

BEst,
Dongyuan

**Comment by XiaPoppy** [comment]
Hi Dongyuan,

Thanks for your reply. For saving time, I checked and run all the things with the **first 100 genes** instead of 500.(still with the same batches 's1d1' and 's1d2')

1. As I checked the identity with codes in R, they are really the same.
```r
matrix_s <- as.matrix(assay(simu_sce))
matrix_ref <- as.matrix(assay(example_sce))

if (all(matrix_s == matrix_ref)) {
    cat("The count matrices are identical.\n")
  } else {
    cat("The count matrices are different.\n")
  }
```
it returns "The count matrices are identical."

2. There are some NA value and also many values **not 0** in `BATCH_para_alter$mean_mat`.

3. tried seeds 1, 23 and 42, but still have the identical count matrix.

Best,
Danyang

**Comment by SONGDONGYUAN1994** [comment]
Hi Danyang,
Could you please reinstall the scDeisgn3 package? The NA values will not show in our newest version. Sorry that I have no idea about your issue. I do have a question: when you use `AnnData2SCE`, does your converted data have the assay `counts`?

@qw130 Hi Qingyang, could you also help us check this issue?

Danyang, if you do not mind, can you send your demo data to our email [dongyuansong@ucla.edu]? Since it is a public dataset, I guess it won't trouble you too much.

Best,
Dongyuan

**Comment by SONGDONGYUAN1994** [comment]
@XiaPoppy 
Hi Danyang,
Your code generates correct results in my server. After checking your description, now I understand what happened to you. Note: your `assay(simu_sce)` does not return your `counts` assay; I think it returns your `X` assay due to the conversion from anndata. Therefore, you haven't change this one in your simulated data, thus it remains the same as the real data.

Could you check `assay(simu_sce, "counts")` and `assay(example_sce, "counts")` instead?

Best,
Dongyuan
